# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='问题')),
                ('userid', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
        migrations.RemoveField(
            model_name='commonuser',
            name='question',
        ),
        migrations.DeleteModel(
            name='commonUser',
        ),
    ]
