# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0002_note_summay'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.TextField(null=True),
        ),
    ]
