# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0002_auto_20180313_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='headImg',
            field=models.FileField(upload_to='F:\\github\\ZC\\TianWen\\media', verbose_name='文件'),
        ),
    ]
